name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Angular dependencies
        working-directory: packages/frontend
        run: npm ci

      - name: Build Angular app
        working-directory: packages/frontend
        run: npm run build
